package com.ecpay.qr;

import com.ecpay.packager.QRBasePackager;
import com.ecpay.packager.QRFieldPackager;
import com.ecpay.packager.QRMsgFieldPackager;
import com.ecpay.primitive.CHAR;
import com.ecpay.primitive.HEX;
import com.ecpay.primitive.NUMERIC;

/**
 * Created by Joe on October, 18 2018 .
 */
public class EPackager extends QRBasePackager {
  protected QRFieldPackager fld[] = {
      /*00*/  new NUMERIC(2, "Payload format indicator"),
      /*01*/  new NUMERIC(2, "Point of initiation method"),
      /*02*/  null,
      /*03*/  null,
      /*04*/  null,
      /*05*/  null,
      /*06*/  null,
      /*07*/  null,
      /*08*/  null,
      /*09*/  null,
      /*10*/  null,
      /*11*/  null,
      /*12*/  null,
      /*13*/  null,
      /*14*/  null,
      /*15*/  null,
      /*16*/  null,
      /*17*/  null,
      /*18*/  null,
      /*19*/  null,
      /*20*/  null,
      /*21*/  null,
      /*22*/  null,
      /*23*/  null,
      /*24*/  null,
      /*25*/  null,
      /*26*/  new QRMsgFieldPackager(new CHAR(99, "Merchant account information"), new MAIPackager()),
      /*27*/  null,
      /*28*/  null,
      /*29*/  null,
      /*30*/  null,
      /*31*/  null,
      /*32*/  null,
      /*33*/  null,
      /*34*/  null,
      /*35*/  null,
      /*36*/  null,
      /*37*/  null,
      /*38*/  null,
      /*39*/  null,
      /*40*/  null,
      /*41*/  null,
      /*42*/  null,
      /*43*/  null,
      /*44*/  null,
      /*45*/  null,
      /*46*/  null,
      /*47*/  null,
      /*48*/  null,
      /*49*/  null,
      /*50*/  null,
      /*51*/  null,
      /*52*/  new NUMERIC(4, "Merchant category code"),
      /*53*/  new NUMERIC(3, "Transaction currency"),
      /*54*/  new CHAR(13, "Transaction amount"),
      /*55*/  new NUMERIC(2, "Tip or convenience indicator"),
      /*56*/  new CHAR(13, "Value of convenience fee fixed"),
      /*57*/  new CHAR(5, "Value of convenience fee percentage"),
      /*58*/  new CHAR(2, "Country code"),
      /*59*/  new CHAR(25, "Merchant name"),
      /*60*/  new CHAR(15, "Merchant city"),
      /*61*/  new CHAR(10, "Postal code"),
      /*62*/  new QRMsgFieldPackager(new CHAR(99, "Additional data field template"), new ADFTPackager()),
      /*63*/  new HEX(4, "Cyclic redundancy check - CRC"),
      /*64*/  null,
      /*65*/  null,
      /*66*/  null,
      /*67*/  null,
      /*68*/  null,
      /*69*/  null,
      /*70*/  null,
      /*71*/  null,
      /*72*/  null,
      /*73*/  null,
      /*74*/  null,
      /*75*/  null,
      /*76*/  null,
      /*77*/  null,
      /*78*/  null,
      /*79*/  null,
      /*80*/  null,
      /*81*/  null,
      /*82*/  null,
      /*83*/  null,
      /*84*/  null,
      /*85*/  null,
      /*86*/  null,
      /*87*/  null,
      /*88*/  null,
      /*89*/  null,
      /*90*/  null,
      /*91*/  null,
      /*92*/  null,
      /*93*/  null,
      /*94*/  null,
      /*95*/  null,
      /*96*/  null,
      /*97*/  null,
      /*98*/  null,
      /*99*/  null
  };

  public EPackager() {
    super();
    setFieldPackager(fld);
  }
}
